version: 2
jobs:
  test-python-3.7: &template
    docker:
      - image: circleci/python:3.7

    working_directory: ~/nyoibo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements_dev.txt
      - run:
          name: xenon
          command: sh run_xenon.sh
      - run:
          name: run tests
          command: sh run_tests.sh

  test-python-3.6:
    <<: *template
    docker:
      - image: circleci/python:3.6

  test-python-3.8:
    <<: *template
    docker:
      - image: circleci/python:3.8

  test-python-3.9:
    <<: *template
    docker:
      - image: circleci/python:3.9

  test-python-3.10:
    <<: *template
    docker:
      - image: circleci/python:3.10


workflows:
  version: 2
  test:
    jobs:
      - test-python-3.7
      - test-python-3.8
      - test-python-3.9
